name: Deploy new version to pypi

on:
  push:
    branches: [ test_build ]
    paths:
      - 'setup.py'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/sbioapputils
    permissions:
      id-token: write
    steps:
    - name: Retrieve distributions
      run: python setup.py sdist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
